"""initial schema

Revision ID: e3f214f2036e
Revises:
Create Date: 2026-08-28 17:49:00.205232

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3f214f2036e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('posting_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seeker_id', 'posting_id')
    )
    op.create_index(op.f('ix_applications_posting_id'), 'applications', ['posting_id'], unique=False)
    op.create_index(op.f('ix_applications_seeker_id'), 'applications', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_seeker_id'), 'audit_events', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_audit_events_ts'), 'audit_events', ['ts'], unique=False)
    op.create_table('dead_letters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(length=2048), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letters_application_id'), 'dead_letters', ['application_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_seeker_id'), 'dead_letters', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_task_id'), 'dead_letters', ['task_id'], unique=False)
    op.create_index(op.f('ix_dead_letters_task_type'), 'dead_letters', ['task_type'], unique=False)
    op.create_table('domain_throttles',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('next_allowed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_usage_seeker_id'), 'llm_usage', ['seeker_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('posting_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rerank_score', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seeker_id', 'posting_id')
    )
    op.create_index(op.f('ix_matches_posting_id'), 'matches', ['posting_id'], unique=False)
    op.create_index(op.f('ix_matches_seeker_id'), 'matches', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('postings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postings_canonical_url'), 'postings', ['canonical_url'], unique=True)
    op.create_index(op.f('ix_postings_content_hash'), 'postings', ['content_hash'], unique=False)
    op.create_table('preferences',
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('seeker_id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seeker_id', 'version')
    )
    op.create_index(op.f('ix_profiles_seeker_id'), 'profiles', ['seeker_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('posting_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_seeker_id'), 'resumes', ['seeker_id'], unique=False)
    op.create_table('seekers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_ref', sa.String(length=255), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('seeker_id', sa.String(length=32), nullable=False),
    sa.Column('application_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=2048), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_application_id'), 'tasks', ['application_id'], unique=False)
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_tasks_seeker_id'), 'tasks', ['seeker_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_seeker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_application_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('seekers')
    op.drop_index(op.f('ix_resumes_seeker_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_profiles_seeker_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_postings_content_hash'), table_name='postings')
    op.drop_index(op.f('ix_postings_canonical_url'), table_name='postings')
    op.drop_table('postings')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_seeker_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_posting_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_llm_usage_seeker_id'), table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_table('domain_throttles')
    op.drop_index(op.f('ix_dead_letters_task_type'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_task_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_seeker_id'), table_name='dead_letters')
    op.drop_index(op.f('ix_dead_letters_application_id'), table_name='dead_letters')
    op.drop_table('dead_letters')
    op.drop_index(op.f('ix_audit_events_ts'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_seeker_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_seeker_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_posting_id'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
